config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logins#index'
  # get 'matelpage/index' => 'matelpage#index'
  # root 'matelpage#index'
  # get '/posts', to: 'posts#show'
  # post '/posts/create', to: 'posts#create'
  get '/mystery_lists', to: 'mystery_lists#index'
  # resource :mystery_lists
  resource :posts do
    collection do
      get :list
    end
  end
  resource :basics, only: [:show] do
    collection do
      post :answer
    end
  end
  resource :questions, only: [:show] do
    collection do
      post :answer
    end
  end
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController

  # 謎解き問題詳細
  def show
    @basic = Post.all.where(challenge_level: params[:challenge_level], display_order: params[:display_order]).first
    if params[:incorrect]
      @incorrect = '解答が違います。'
    end

    if ! @basic.present?
      render :end
    end
  end

  # 謎解き問題解答
  def answer
    @basic = Post.all.where(challenge_level: params[:challenge_level], display_order: params[:display_order]).first
    if @basic.answer == permit_answer_params[:send_answer]
      render :answer
    else
      redirect_to basics_path(challenge_level: params[:challenge_level], display_order: params[:display_order], incorrect: true)
    end

  end

  private
    def permit_answer_params
      params.require(:post).permit(:send_answer)
    end

end

app/views/basics/answer.html.erb
<main>
  <div class="container">
    <div class="flex">
      <h3 class="header">謎解き<%= @basic&.challenge_level_i18n %>問題</h3>
    </div>
    <h3><%= @basic&.display_order %>問目の答え</h3>
    <%= image_tag @basic&.answer_image.url, :height => "200", :style => "border: 3px #000000 solid;" %>

    <%= content_tag :span, @basic&.answer_text %>

    <%= link_to '前の問題へ', basics_path(:challenge_level => @basic.challenge_level, :display_order => @basic.display_order), class: 'waves-effect waves-light btn' %>
    <%= link_to '次の問題へ', basics_path(:challenge_level => @basic.challenge_level, :display_order => @basic.display_order + 1), class: 'waves-effect waves-light btn' %>
  </div>
</main>

app/views/basics/end.html.erb
<h2>おわり</h2>

<%= link_to '一覧に戻る', mystery_lists_path, class: 'waves-effect waves-light btn' %>

app/views/basics/show.html.erb
<main>
  <div class="container">
    <div class="flex">
      <h3 class="header">謎解き<%= @basic&.challenge_level_i18n %>問題</h3>
    </div>
    <h4><%= @basic&.display_order %>問目</h4>
    <%= image_tag @basic&.question_image.url, :height => "200", :style => "border: 3px #000000 solid;" %>
    <% if @basic&.hints.count > 0 %>
      <ul class="collapsible">
        <% @basic&.hints.each_with_index do |hint, index| %>
          <li>
            <div class="collapsible-header"><i class="material-icons"></i>ヒント<%= index + 1 %></div>
            <div class="collapsible-body"><%= content_tag :span, hint&.hint %></div>
          </li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for :post, url: answer_basics_path, method: :post do |f| %>
      <%= hidden_field_tag :display_order, @basic.display_order %>
      <%= hidden_field_tag :challenge_level, @basic.challenge_level %>
      <p><%=f.label @basic.remarks %><br><%= f.text_field :send_answer %></p>
      <button class="btn waves-effect waves-light" type="submit" name="action">送信
        <i class="material-icons right">send</i>
      </button>
    <% end %>

    <% if @incorrect.present? %>
      <%= @incorrect %>
    <% end %>
    <br>
    <%= link_to '一覧に戻る', mystery_lists_path, class: 'waves-effect waves-light btn' %>
  </div>
</main>
<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>