config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logins#index'
  # get 'matelpage/index' => 'matelpage#index'
  # root 'matelpage#index'
  # get '/posts', to: 'posts#show'
  # post '/posts/create', to: 'posts#create'
  get '/mystery_lists', to: 'mystery_lists#index'
  # resource :mystery_lists
  resource :posts do
    collection do
      get :list
    end
  end
  resource :basics, only: [:show] do
    collection do
      post :answer
    end
  end
  resource :questions, only: [:show] do
    collection do
      post :answer
    end
  end
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/index.html.erb
<h1>Welcome#index</h1>
 
<% if user_signed_in? %>
  <%= link_to 'プロフィール変更', edit_user_registration_path %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

  <%= link_to '投稿する', new_posts_path %>
  <%= link_to '投稿一覧', list_posts_path %>

  <% @posts.each do |post| %>
    <p><%= post.title %></p>
    <%= image_tag post&.question_image.url, :height => "200", :style => "border: 3px #000000 solid;" %>
    <%= link_to questions_path(id: post.id) do %>
      詳細を見る
    <% end %>
    <%= link_to user_path(post&.user_id), class: 'collection-item' do %>
      <%= post&.user&.username %>さんの投稿一覧
    <% end %>
  <% end %>

<% else %>
  <%= link_to 'ユーザー登録', new_user_registration_path %>
  <%= link_to 'ログイン', new_user_session_path %>
<% end %>