config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logins#index'
  # get 'matelpage/index' => 'matelpage#index'
  # root 'matelpage#index'
  # get '/posts', to: 'posts#show'
  # post '/posts/create', to: 'posts#create'
  get '/mystery_lists', to: 'mystery_lists#index'
  # resource :mystery_lists
  resource :posts do
    collection do
      get :list
    end
  end
  resource :basics, only: [:show] do
    collection do
      post :answer
    end
  end
  resource :questions, only: [:show] do
    collection do
      post :answer
    end
  end
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ##
  # リレーション
  ##
  has_many :posts

  ##
  # バリデーション
  ##
  validates :username, presence: true, length: { maximum: 50 }

  ##
  # scopes
  ##
  # 投稿(内部)
  scope :with_inner_posts, -> { joins(:posts).eager_load(:posts) }

  # 投稿(外部)
  scope :with_posts, -> { eager_load(:posts) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.with_posts
  end

  def show
    @user = User.find(params[:id])
  end

end

app/views/users/index.html.erb
  <% @users.each do |user| %>
    <%= user.id %>
    <%= user.username %>
    <%= link_to users_path(id: user.id), class: 'collection-item' do %>
      <%= user.username %>さんの投稿一覧
    <% end %>
  <% end %>

app/views/users/show.html.erb
<%= @user.username %>さんの投稿

<% @user.posts.each do |post| %>
  <p><%= post.title %></p>
  <%= image_tag post&.question_image.url, :height => "200", :style => "border: 3px #000000 solid;" %>
  <%= link_to questions_path(id: post.id) do %>
    詳細を見る
  <% end %>
<% end %>